Add ', to jump to the executing line across files
cgdb/cgdb pull request #316
Opened 2022-04-20 08:16 UTC by gahr

The '. jump command only resolves the currently executing line in the
currently displayed buffer. When navigating source files, it's sometimes
convenient to be able to jump back to the currently executing line
across files. I've implemented ', as a variation of '. to do that.

Alternatively, if preferred, I can also implement the feature in the
original '. command.

Signed-off-by: Pietro Cerutti <gahr@gahr.ch>

2022-04-29 23:19 UTC, brasko commented
My instinct is that this should be merged into the '. command. That is, the '. feature should have done this in the first place.
@mikesart Do you have any thoughts?
Also, could you move the currently executing node to the line below?
    /* Set executing line if passed a valid value */
    if (exe_line == -1) { 
        sview->cur->exe_line = -1;
    } else if (exe_line > 0) {
----> Set the currently executing node here?
        sview->cur->exe_line = clamp_line(sview, exe_line - 1);
    }

2022-04-30 15:15 UTC, gahr commented
I've applied the suggested change. I'll wait for feedback whether I should merge this with `'.`

2022-05-25 01:56 UTC, brasko commented
@gahr Lets merge it with the '. command. Is that your preference as well?

2022-08-19 02:34 UTC, brasko requested changes

2022-08-19 02:34 UTC, brasko commented on doc/cgdb.texi
> +Jump to the currently executing line cross files.
This language is a bit confusing. I would either leave it unchanged, or change it to something like "Jump to the currently executing file and line"

2022-08-19 02:34 UTC, brasko commented on cgdb/sources.h
> +    struct list_node *cur_exe;             /* Current node we're executing */
This needs to be initialized to NULL in sources.cpp:source_new I would imagine.

2022-08-19 02:34 UTC, brasko commented on cgdb/sources.cpp
> +        sview->cur_exe = sview->cur;
There is something about this that doesn't seem right to me. However, I can't pin it down at the moment.
I think it's that i'm seeing the cur executing node being saved away, but the current executing line going into sview->cur instead of sview->cur_exe. Later, above, I see you using sview->cur_exe->exe_line. I'm guessing that won't always have the right value. I would have to test this however to be sure. Can you think about this a bit and see if I'm on to something?

2022-08-19 07:10 UTC, gahr commented on cgdb/sources.cpp
> +        sview->cur_exe = sview->cur;
I think I'm saving cur into cur_exe, including the executing line. Would if help if I swapped the two lines? Assuming I understand your point :)

```cpp
sview->cur->exe_line = clamp_line(sview, exe_line - 1);
sview->cur_exe = sview->cur;
```

2022-08-19 11:32 UTC, brasko commented
Great job, thanks, this has been merged

2022-08-19 11:32 UTC, closed without merging